---
pagetitle: "Home | R3"
output:
  html_document:
    toc: false
    code_folding: null
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview {.unnumbered}

This website is the starting point for the free 8-week webinar training
series on **Reproducible Reporting with R** (R^3^) for ***marine
ecological indicators***, sponsored by the Working Group on the
Northwest Atlantic Regional Sea
([WGNARS](https://www.ices.dk/community/groups/Pages/WGNARS.aspx)) and
open to all.

Materials will be populated into the Schedule below and menu above.
Please consult the [**Setup**](./setup.html) to have accounts created
and software installed.

## Webinar

Please join the WebEx meeting here Mondays 2-3:30 pm Eastern time:

[Webex: Open Sci Short Course, hosted by
NEFSC](https://noaanmfs-meets.webex.com/noaanmfs-meets/j.php?MTID=m48bc0a9e0d4ff76970e2ba6df1a1a574)

The first hour will be a presentation and the last half hour for
discussion and exercise completion time. All webinars will be
***recorded*** and posted to this website for future reference.

## Schedule

<!-- TODO: as bootstrap cards with icons -->

1.  June 14: **Collaborate**\
    Use Github to share and version code, as well as handle basic
    project management with issues and project boards. The RStudio
    development environment will be introduced to interface with git and
    Github. Use of Github Pages to host knitted Rmarkdown documents will
    enable sharing of online reports.\
    [Video](https://youtu.be/KHaIlNxNjNA), [Slides](https://docs.google.com/presentation/d/1AXuQhSfQ3w-3Hv7BV6PT3yLsPqxJcY52UXTlQr1ytoM/edit#slide=id.p), [Lesson](./collaborate.html) \
    \
2.  June 21: **Manipulate**\
    Use the latest "tidyverse" of R packages (readr, dplyr, tidyr,
    stringr, lubridate) for wrangling data and sequencing operations
    with the pipe (%\>%) operator.\
    [Video](https://youtu.be/KncPglQcyKU), 
    [Slides](https://docs.google.com/presentation/d/1lilrIzlD5Y2vPEax4fao8GqS-TsxSzNMfyGPgKr7TlM/edit?usp=sharing), [Lesson](./manipulate.html) \
    \
3.  June 28: **Visualize**\
    Use principles of the "grammar of graphics" to develop static plots
    in the R package ggplot2. Make these interactive with plotly.
    Develop dedicated time series plots with dygraphs.\
    [Video](https://youtu.be/h8fR2czCRr0), [Slides](https://docs.google.com/presentation/d/1AS6beW02Upzv4vi5RgK_mwi0o740Q5l0kgCMsKOCmos/edit?usp=sharing), [Lesson](./visualize.html) \
    \
4.  July 12: **Map**\
    Read and write vector data (points, lines, polygons) using the
    spatial features sf R package in conjuction with dplyr to wrangle
    and summarize. Use the raster R package for gridded data. Generate
    interactive maps with leaflet.\
    [Video](https://youtu.be/tQ4gv8WLxrw), [Slides](https://docs.google.com/presentation/d/1ZHqQbGIPa1smv7oXAyu6oOzRWyQ2AFa7M9FC21J_shM/edit#slide=id.p4), [Lesson](./map.html) \
    \
5.  July 19: **Report**\
    Dive into Rmarkdown for for knitting formatted text (markdown) with
    chunks of evaluated R code into html, pdf and docx formats. Use
    Rmarkdown for single page reports, bookdown for reports with
    chapters, flexdashboard for dashboards and Rmarkdown websites for
    simple websites with shared navigation. Automatically render with
    Github Actions.\
    [Video](https://youtu.be/kPoBnWY4xqg), [Slides](https://docs.google.com/presentation/d/15I1i1bw1lyKeFYA1p2d98fvhR8DjD9J66zBUCC7c2g8), [Lesson](./report.html) \
    \
6.  July 26: **Infographics**\
    Use a custom infographiq Javascript library to intelligently link
    icons of ecosystem elements to pop-up windows containing data figures, which
    could be static images or interactive visualizations.\
    [Video](https://youtu.be/wQn05c8CHhs), [Slides](https://docs.google.com/presentation/d/11UFk-6k7oKJcnziBbkNYSz5Miq8SVUEiY5UmI3nWUDA/edit#slide=id.p), [Lesson](./infographics.html) \
    \
7.  August 2: **Applications**\
    Use the Shiny framework to develop online interactive applications
    accepting user input to render outputs from arbitrary R functions.
    Server requirements differentiating from simpler Rmarkdown
    renderings will be reviewed as well as use of Crosstalk to gain
    similar functionality with Rmarkdown with simple data.\
    [Video](https://youtu.be/ELDb_KB81jk), [Slides](https://docs.google.com/presentation/d/19XTk3sT9InpVlltTBa3TUm50Uv8gE_v0_3wjuNxx8WA/edit?usp=sharing), [Lesson](./apps.html) \
    \
8.  August 9: **Packages**\
    An R package is a documented set of functions that can act as
    building blocks for data ingestion, analysis, visualization and
    reporting. We'll go over the basics of creating an R package and
    documenting functions within.\
    [Slides](https://docs.google.com/presentation/d/1Jt4xZP7twPoykHzyblMMRVGxgt9weUN1111OOKdkPU8/edit?usp=sharing), [Lesson](./packages.html) \
    \
