---
title: "Resources"
output:
  html_document:
    code_folding: null
    number_sections: false
    pandoc_args: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting Started with R & RStudio

* [Getting Started with R | RStudio Support](https://support.rstudio.com/hc/en-us/articles/201141096-Getting-Started-with-R)
* [Getting started with R and RStudio | ourcodingclub](https://ourcodingclub.github.io/tutorials/intro-to-r/)
* [Beginner - Learn | RStudio Education](https://education.rstudio.com/learn/beginner/)
* [Chapter 1 Getting Started with Data in R | Statistical Inference via Data Science](https://moderndive.netlify.app/1-getting-started.html) _A ModernDive into R and the Tidyverse_
* [A Gentle Introduction to Tidy Statistics in R - RStudio](https://www.rstudio.com/resources/webinars/a-gentle-introduction-to-tidy-statistics-in-r/)
* [Unit 1: Basic Basics | R-Ladies Sydney](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-0/)
  * [1.1 An opinionated tour of RStudio](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-1/)
  * [1.2 Installing and loading packages](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-2/)
  * [1.3 Getting data into RStudio](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-3/)
* [Primers | RStudio Cloud](https://rstudio.cloud/learn/primers)
  * [The Basics](https://rstudio.cloud/learn/primers/1)
    * [Data Visualization Basics](https://rstudio.cloud/learn/primers/1.1)
    * [Programming basics](https://rstudio.cloud/learn/primers/1.2)
  * [Work with Data](https://rstudio.cloud/learn/primers/2)
  * [Visualize Data](https://rstudio.cloud/learn/primers/3)
  * [Tidy Your Data](https://rstudio.cloud/learn/primers/4)
  * [Iterate](https://rstudio.cloud/learn/primers/5)
  * [Write Functions](https://rstudio.cloud/learn/primers/6)
* [Introduction to R | Data Carpentry](https://datacarpentry.org/R-ecology-lesson/01-intro-to-r.html)
* [Data Analysis and Visualization in R for Ecologists | Data Carpentry](https://datacarpentry.org/R-ecology-lesson/)
* [Chapter 2 R basics and workflows | UBC STAT 545](https://stat545.com/r-basics.html)

## Cheatsheets

[RStudio Cheatsheets - RStudio](https://www.rstudio.com/resources/cheatsheets/)

- [RStudio Essentials - RStudio](https://www.rstudio.com/collections/rstudio-essentials/)

## Online Books

- [R for Data Science](http://r4ds.had.co.nz/)
- [Spatial Data Analysis and Modeling with R](http://rspatial.org)

## Online Courses

* [Practical R Workflow for Scientists June-July 2021](https://rverse-tutorials.github.io/RWorkflow-NWFSC-2021/)
* [Software Carpentry](https://software-carpentry.org/lessons/)
* [Data Carpentry](https://datacarpentry.org/lessons/)
* [R for Excel Users](https://rstudio-conf-2020.github.io/r-for-excel/)

* [Reproducible science with R, RStudio, and GitHub at MBARI: Nov 30 - Dec 1, 2017](https://jules32.github.io/2017-11-30-MBARI/)


## Visualize

* [The Grammar and Graphics of Data Science - RStudio](https://www.rstudio.com/resources/additional-talks/the-grammar-and-graphics-of-data-science/)

## Applications

* [Shiny - Tutorial](https://shiny.rstudio.com/tutorial/?_ga=2.141207218.1461543799.1623615738-155442495.1623419383)
